
// import "@mantine/core/styles.css";
"use client"
import "./globals.css";

import "@fortawesome/fontawesome-free/css/all.min.css";
import "bootstrap-css-only/css/bootstrap.min.css";
import "mdbreact/dist/css/mdb.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ThemeContextProvider } from "@/context/context";
import SideBar from "@/components/Sidebar/page";

import { MantineProvider } from "@mantine/core";



import { ThemeProvider, THEME_ID, createTheme } from '@mui/material/styles';

const inter = Inter({ subsets: ["latin"] });


// export const metadata: Metadata = {
  
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

const materialTheme = createTheme({
  spacing: 4,
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeContextProvider>
        <ThemeProvider theme={{ [THEME_ID]: materialTheme }}>
        <div className="d-flex">
          <SideBar />

          <div className="w-70">

              
          {children}

          </div>

        </div>

           </ThemeProvider>

        </ThemeContextProvider>
      </body>
    </html>
  );
}
